### ISSUE TITLE
Editing submission Q&As add quotes around the edited fields

### ISSUE THREAD

**Issue by nerdalert** [instructlab/ui#35]
For example:

```yaml
 - question: h2424
    context: h244h
    answer: h24222
  - question: fds
    context: '123456789'
    answer: '1234567890'
  - question: '12345'
    context: ''
    answer: '6789'
```

Modifying `yaml.dump` in `src/app/edit-submission/skill/[id]/page.tsx` should resolve it.
